version: '3.1'
services:
  app:
    build: ./
    command: ["wait-for-it.sh", "devbox:8080", "--strict", "--timeout=0", "--", "gunicorn", "main:create_app", "--worker-class", "aiohttp.worker.GunicornWebWorker", "-b", "0.0.0.0:8081", "--reload"]
    depends_on:
      - devbox
    links:
      - devbox
    env_file:
      - .env
    ports:
      - "8081:8081"
      - "8082:8082"
    volumes:
      - .:/app:cached
      - ./wait-for-it.sh:/usr/local/bin/wait-for-it.sh
  devbox:
    image: "healthsamurai/devbox:0.4.7"
    depends_on:
      - devbox-db
    links:
      - "devbox-db:database"
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./wait-for-it.sh:/usr/local/bin/wait-for-it.sh
      - ./config:/var/config:cached
  devbox-db:
    image: "aidbox/db:11.4.0.3"
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devbox